# Requires 3 varialbes to be set:
# satellite_hostname: Hostname of Satellite server
# activation_key: Activation key to use when registering
# organization: Organization to use when registering
#
# Note: This can be set inside Tower template, 
#       or (recommended) as variables for each group in the inventory
---

- name: Register clients to Satellite server
  hosts: all
  become: yes
  roles:
    - role: register
