---
- name: Generate registration command
  redhat.satellite.registration_command:
    server_url: "{{ satellite_host }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    activation_keys: "{{ activation_keys }}"
    location: "{{ location }}"
    organization: "{{ organization }}"
    operatingsystem: "{{ operating_system }}"
    update_packages: "{{ update_packages }}"
    insecure: true
    validate_certs: false
    jwt_expiration: 1
  register: command

- name: Show registration command
  debug:
    verbosity: 1
    var: command

- name: Perform registration
  ansible.builtin.shell:
    cmd: "{{ command.registration_command }}"
