---
- name: Uninstall Satellite certificate
  ansible.builtin.package:
    name: katello-ca-consumer-*
    state: absent

- name: Install Satellite certificate
  ansible.builtin.package:
    name: http://{{ satellite_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm
    state: present

- name: Register to Satellite
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ activation_key }}"
    org_id: "{{ organization }}"
    force_register: yes
