---
- name: Generate Satellite registration token
  redhat.satellite.registration_command:
    server_url: "{{ satellite_host }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    activation_keys: "{{ activation_keys }}"
    location: "{{ location }}"
    organization: "{{ organization }}"
    operatingsystem: "{{ operating_system }}"
    update_packages: "{{ update_packages }}"
    insecure: true
    validate_certs: false
    jwt_expiration: 1
  register: command

- name: Register client to Satellite
  ansible.builtin.shell:
    cmd: "{{ command.registration_command }}"
  register: command_result
  ignore_errors: true
  failed_when:
    - command_result.rc >= 1
    - '"This system is already registered" not in command_result.stderr'
  changed_when: command_result.rc == 0
