---
# Perform update on clients
- name: Perform full package update
  block: 
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      # Uncomment this line to simulate failure
      # by disabling all repositories, so yum
      # returns an error.
      #
      # disablerepo: "*"
    register: yum_output

  # This section is run when an error
  # was encountered. Send notification
  # email with the error output.
  rescue:
  - name: Send email on failure
    mail:
      host: "{{ email_server }}"
      port: "{{ email_server_port }}"
      username: "{{ email_username }}"
      password: "{{ email_password }}"
      to: "{{ email_recipient_list }}"
      from: "{{ email_sender }}"
      subject: "Ansible: Patching failure on {{ inventory_hostname }}"
      body: "System {{ inventory_hostname }} encountered an error while patching.\n\nJob output:\n\n{{ yum_output.msg }}"
    delegate_to: localhost
