---
# Perform update on clients
- name: Perform full package update
  block: 
  - name: Update all packages
    yum:
      name: '*'
      state: latest
      # Uncomment this line to simulate failure
      # by disabling all repositories, so yum
      # returns an error.
      #
      # disablerepo: "*"
    register: yum_output

  # This section is run when an error
  # was encountered. Capture the notification
  # message into a temporary file in order to
  # send a single email afterwards.
  rescue:
  - name: Capture failure message
    shell: echo -e "System {{ inventory_hostname }} encountered an error while patching.\n\nJob output:\n\n{{ yum_output.msg }}\n==========" >> /tmp/yum-output
    delegate_to: localhost
